OperationCode/operationcode_backend

- Gemfile
- Gemfile.lock
- config/initializers/cors.rb
> Adds CORS. Fixes #11

- app/controllers/api/v1/users_controller.rb
- test/models/user_test.rb
Allows user to set their password on sign up
Fixes #15
> Allows user to set their own password. Fixes #15

- Gemfile
- Gemfile.lock
- app/models/user.rb
- test/models/user_test.rb
Adds geocoding on user creation
Fixes #1
> Adds geocoding. Fixes #1

- config/code_schools.yml
- Typos corrected
- Schools added
- MakerSquare removed (absorbed by Hack Reactor)
- Logo paths added to schools missing a logo
- `has_online` and `online_only` booleans added to each school
Fixes #26
> Make various changes to code_schools.yml

- .travis.yml
Simplifies travis config
Fixes #30
> Updates travis config. Fixes #30

- Makefile
- app/controllers/api/v1/events_controller.rb
- app/models/event.rb
- config/code_schools.yml
- config/routes.rb
- db/migrate/20170613012405_create_events.rb
- db/migrate/20170616161847_change_url_to_url.rb
- db/schema.rb
- test/factories/events.rb
- test/models/event_test.rb
Add event endpoint with index action per issue #6.  This pull request adds an events controller with an index action that renders all events in a json format.   This request also adds a model with validations.  The validation for websites is currently set to start with "www.".  The validation does not catch "www.."  It will reject ftp and other sites not starting with www.  Currently allows URL, end_date, and address2 to be empty.  Also created the events table with a migration.  Added events route to routes.rb.  
Fixes #6
> Events endpoint Issue #6

- config/code_schools.yml
As discussed with Conrad, I include RMOTR into the list of online schools
> Include RMOTR into online schools

- Gemfile
- Gemfile.lock
- config/environments/production.rb
Adds sentry reporting
Fixes #59
> Adds sentry. Fixes #59

- config/code_schools.yml
Please pull https://github.com/OperationCode/operationcode_backend/pull/56 first.
Adjust YAML to accept images via master branch of GitHub repo as opposed to another branch.
No issue resolved.
> Edit Image URI path

- config/code_schools.yml
Wyncode Academy is VA approved to accept the GI Bill.
> Added Wyncode Academy as a VA Approved Coding Bootcamp

- Gemfile
- Gemfile.lock
- app/jobs/add_user_to_send_grid_job.rb
- app/lib/send_grid_client.rb
- app/lib/send_grid_client/response.rb
- app/models/user.rb
- run/secrets/sendgrid_api_key
- test/jobs/add_user_to_send_grid_job_test.rb
- test/lib/send_grid_client_test.rb
- test/models/user_test.rb
Adds a new job to run when a user signs up to add them to our sendgrid contact list.
Fixes #49
> Adds send grid job. Fixes #49

- Dockerfile
- Makefile
- bin/deploy
- bin/publish
- config/database.yml
Fixes to get us up and running on k8s.
Fixes #97
> K8s migration

- app/controllers/api/v1/sessions_controller.rb
- app/lib/discourse/single_sign_on.rb
- app/models/user.rb
- config/initializers/devise.rb
- run/secrets/discourse_sso_secret
- test/controllers/api/v1/sessions_controller_test.rb
- test/models/user_test.rb
Adds logic for discourse SSO logins
Fixes #91
> SSO Redirect

- config/code_schools.yml
This is just to update our address to reflect our website, as well as to add our brand new Java, Android & Salesforce bootcamp. Our Java bootcamp recently was approved by the GI bill.
Fixes #
> updated full stack info and added java, android & salesforce bootcamp info

- config/code_schools.yml
Remove schools  list as mentioned here:
- Dev Bootcamp [#107](https://github.com/OperationCode/operationcode_backend/issues/107) 
- Iron Yard [#106](https://github.com/OperationCode/operationcode_backend/issues/106) 
- RefactorU [#99](https://github.com/OperationCode/operationcode_backend/issues/99)
Schools shut down
Fixes #99 
Fixes #106 
Fixes #107
> Update school list

- README.md
Update ruby version from 2.3.1 to 2.3.3 as  in `.ruby-version`
Fixes #
> Update Ruby Version

- config/code_schools.yml
add DevPoint Labs to the VA approved section of the site. Also if we can use this logo attach below on it, that would be great.
Thanks
> added DevPoint Labs to code school yml file

- app/controllers/api/v1/users_controller.rb
- config/routes.rb
- db/migrate/20170806214216_add_additional_fields_for_profiles_to_users.rb
- db/migrate/20170809164559_add_scholarship_info_field_to_users.rb
- db/schema.rb
- test/controllers/api/v1/users_controller_test.rb
Extending from #134 
Fixes #133
> Cooperbuilt master

- app/views/user_mailer/welcome.html.erb
Currently, the email displays '0+' users. I just jumped in and made it '3000+' as per our current database.
> Fix user count

- README.md
Ensure contributors know that they need to update the docs too.
> Add mention of Apiary to contributors

- app/controllers/api/v1/scholarship_applications_controller.rb
- app/controllers/api/v1/scholarships_controller.rb
- config/routes.rb
- db/migrate/20170821193457_change_scholarship_application.rb
- db/schema.rb
Adds Scholarship and ScholarshipApplications endpoints to API so that verified users can apply for scholarships
Fixes #144
> Create scholarship controller

- config/team_members.yml
- db/seeds.rb
- test/models/team_member_test.rb
Adds Team Members to db via seed
Team Members are listed in config/team_members.yml
Created model test to provide additional coverage for TeamMember model
Fixes #130
> Team Members created when seeding db

- app/models/scholarship_application.rb
- config/locales/en.yml
Adds uniqueness validation to Scholarship Application model so that a user may only submit one application per scholarship
Fixes #158
> adds uniqueness validator

- config/code_schools.yml
The purpose of this PR is to add Rithm School into code_school.yml. The information was also updated with the link to the logo.
Fixes #121
> resolve #121

- app/views/user_mailer/welcome.html.erb
Adds our Discourse forums to our introductory email.
> Added forum references

- README.md
Updating the README to quickly provide critical information for Hacktoberfest participants.
> Update README to filter Hacktoberfest participants

- config/initializers/sidekiq.rb
Sets the `sidekiq` database URL to be dynamic with a named fallback
> dynamic-sidekiq-db-name

- config/code_schools.yml
Added SecureSet to school list
Fixes issue #196
> Added SecureSet school to code_schools yaml file

- config/code_schools.yml
As per request of Bootcamp rep: Change link.
> Edit link for Cincy Code It Bootcamp

- config/database.yml
Changes username for new database
> updates database user to new database user

- MAINTAINERS.md
Adds a maintainers file in accordance with [our Open Source Maintenance strategy](https://github.com/OperationCode/START_HERE/blob/master/open_source_maintenance_policy.md)
> adds maintainers file

- MAINTAINERS.md
In keeping with a change to the Maintenance policy, this changes Lieutenant to Sergeant.
> updates lt to sgt

- apiary.apib
Included 3 new Apiary API routes. 
POST  `api/v1/users_controller#create` 
PATCH `api/v1/users_controller#update`
POST for `api/v1/users_controller#verify`
Resolved issue of lacking API docs for users.
Fixes #221
> Issue #221 added api/v1/users documentation 

- apiary.apib
Description of changes
Completes request for Issue #219 adds documentation for:
api/v1/scholarships_controller#index
api/v1/scholarships_controller#show
api/v1/scholarship_applications_controller#create
Issue Resolved
Fixes #219
> Issue #219 Added Scholarship documentations

- config/sidekiq.yml
- docker-compose.yml
Added config file for sidekiq, and adjusted config reference
Fixes `docker-compose up --build` and that error related to sidekiq throwing many exceptions.
> Included config for sidekiq

- apiary.apib
Completes request for Issue #218  adds documentation for:
api/v1/requests_controller#index
api/v1/requests_controller#create
api/v1/requests_controller#show
api/v1/requests_controller#update
Fixes #218
> Issue #218 Added Requests API documentation

- apiary.apib
- app/controllers/api/v1/code_schools_controller.rb
- app/models/code_school.rb
- db/migrate/20180204235116_add_mooc_to_code_schools.rb
- db/schema.rb
- test/factories/code_schools.rb
Add boolean "mooc" to code schools table. See closed PR #236 for discussion. 
Fixes #169
> Added boolean mooc to code schools table

- MAINTAINERS.md
> /feature add me

- MAINTAINERS.md
Reverts OperationCode/operationcode_backend#254
Sorry @wimo7083  - wasnt my repo to merge into >.<
> Revert "/feature add me"

- README.md
Embeds the Travis CI build status badge to the backend's readme
> Adds travis build status to readme

- app/serializers/code_school_serializer.rb
- test/controllers/api/v1/code_schools_controller_test.rb
Adds the code school `mooc` attr to all the endpoint responses, through the serializer.
Fixes #268
> Adds mood to code school serializer

- MAINTAINERS.md
Replaced Lieutenant to Sergeant in MAINTAINERS.md
Fixes #273
> Replaced Lieutenant to Sergeant

- README.md
- docs/setup/aws_vm_setup.md
- This added instructions for running the dev environment in a VM
- changes only in README.md
- no test needed to run
- pattern followed from PR #277 of @hpjaj 
Fixes #
This fixes #271
> Added instructions for running the dev environment in a VM

- apiary.apib
- test/controllers/api/v1/sessions_controller_test.rb
* Updated the description for resources_controller#destroy 
* Updated line 722 on apiary.apib
* No test needed
* add to documentation on apiray.apib for the sessions_controller#create
* tested format by copy pasting onto apiray.io and fixed indentation to make sure it was a valid 
documentation
Fixes #220
> Documentation for sessions_controller#create & resources_controller#destroy

- config/board_members.yml
Updates board member image paths to use absolute S3 URLS
Step 1 of #305 - still need Rake task to be run to update prod DB. ping @hpjaj
> Update board member images to use S3 URLs

- app/admin/team_member.rb
- app/models/ability.rb
Gives admins the ability to conduct CRUD actions on the `TeamMember` model.  
Fixes #307
> 307 teammember in admin

- app/lib/git_hub/client.rb
- app/lib/git_hub/issues.rb
- app/lib/git_hub/pull_requests.rb
- app/lib/git_hub/settings.rb
- lib/tasks/git_hub.rake
Favors GitHub's OAuth2 key/secret auth strategy:
https://developer.github.com/v3/#oauth2-keysecret
Also adds in logging for feedback during the rake process.
> GitHub aggregation users client id and secret

- app/controllers/api/v1/code_schools_controller.rb
- app/models/code_school.rb
- app/serializers/code_school_serializer.rb
- test/factories/code_schools.rb
In development, the query times went from (4 + number_of_schools)ms to 4ms.
* add a default sort order to the locations association on `CodeSchool`
* update `CodeSchoolsController` to include locations in the query result passed to the JSON rendering
* remove the custom `locations()` method from CodeSchoolSerializer to make the serializer rely on the association and default sort ordering already declared
* added a factory for creating a code school with 1-15 locations
Partial fix for #395
With the new `:code_school_with_locations` factory, I created 50 schools from the Rails console. I picked 50 based on the number of schools returned by the endpoint in the production site.
```
> FactoryGirl.create_list(:code_school_with_locations, 50)
```
238ms response time
* db: 50ms
* view: 232ms …
> optimize N+1 query in retrieving CodeSchools with locations

- app/views/user_mailer/welcome.html.erb
Copy updates to the automated email for readability and onboarding. Removes outdated links.
Fixes #382
> Update automated email (fixes #382)

- app/controllers/api/v1/scholarships_controller.rb
- app/models/scholarship.rb
- test/models/scholarship_test.rb
Create an 'Unexpired Scope' which filters out expired scholarships based on `close_time`. Then use this scope for the `scholarships#index`
Fixes #376
> [Issue #376] Filter Expired Scholarships

- CONTRIBUTING.md
The navigation links on this page referred to some content which no longer exists on it. This updates the links to the current headings and removes links to content that would not be visible in an un-expanded state.
None
> Updates navigation of contributing section to reflect current content structure

- CODE_OF_CONDUCT.md
Just a simple tense change to make the wording in the Our Pledge section of the Code of Conduct flow better.
> Changed word 'making' to 'make' in code of conduct

- app/views/user_mailer/welcome.html.erb
Since these are done manually we want to set more realistic expectations.
> increase expectations

- app/controllers/api/v1/users/passwords_controller.rb
- app/models/user.rb
- app/views/devise/mailer/reset_password_instructions.html.erb
- config/environments/development.rb
- config/routes.rb
Fixes #379
- Explicitly sets the password updates, fixes the fact we use `encrypted_password` which was preventing the password from actually updating. 
- Changes routes so they are aligned `/api/v1`
- Adds password update so that FE can allow users to change it.
> Password fix

- app/controllers/api/v1/users/passwords_controller.rb
> remove attribute call

- app/models/user.rb
- config/routes.rb
Disables user validation for password resets.
> Modify validation for password reset

- app/models/user.rb
I added these validations to allow password reset. Now validations only occur on create for zip code, so this isn't needed. 
Code cleanup now that we have a better way of doing this.
> remove duplicate cancelled validation

- app/jobs/slack_jobs/inviter_job.rb
Changes auto-join slack channel from #random to #career-advice
Fixes #
> changed auto-join slack channel to #career-advice

- app/jobs/slack_jobs/inviter_job.rb
This changes the message on request by Conrad.
> change message to be shorter

- app/lib/airtable/mentorship.rb
- app/lib/slack/utils.rb
- test/requests/airtable/mentorship_test.rb
This should validate the slack username if this client is still working. Can't test locally because I don't have the creds
> add slack username validation

- app/lib/airtable/mentorship.rb
- app/lib/slack/utils.rb
Reverts OperationCode/operationcode_backend#474
> Revert "add slack username validation"

- app/lib/airtable/mentorship.rb
- app/lib/slack/client.rb
- app/lib/slack/utils.rb
> Want to try with the correct slack domain

- app/lib/airtable/mentorship.rb
- app/lib/slack/utils.rb
- config/environments/development.rb
- test/requests/airtable/mentorship_test.rb
Trying to fix the issues with the method names
> Slack validation

- app/lib/slack/utils.rb
- config/environments/development.rb
> remove raven config

- app/lib/slack/utils.rb
> fix kwargs function

- app/lib/discourse/single_sign_on.rb
- app/lib/meetup.rb
- app/lib/operation_code.rb
- app/lib/send_grid_client.rb
- app/lib/slack/utils.rb
- config/cable.yml
- config/database.yml
- config/environments/production.rb
- config/secrets.yml
> removed fetch_secrets, set defaults for staging

- Rakefile
- app/lib/discourse/single_sign_on.rb
- app/lib/slack/utils.rb
- config/environments/production.rb
- test/controllers/api/v1/sessions_controller_test.rb
Fixes #
commas
remove forgotten include.
> fix the compile and includes

- config/environments/production.rb
- run/secrets/airtable_add_user_base_id
- run/secrets/airtable_add_user_table_name
- run/secrets/airtable_api_key
- run/secrets/discourse_sso_secret
- run/secrets/mailchimp_api_key
- run/secrets/mailchimp_list_id
- run/secrets/meetup_api_key
- run/secrets/new_relic_key
- run/secrets/postgres_password
- run/secrets/postgres_user
- run/secrets/sendgrid_api_key
- run/secrets/sendgrid_password
- run/secrets/sendgrid_username
- run/secrets/slack_subdomain
- run/secrets/slack_token
- run/secrets/split_password
- run/secrets/split_username
- run/secrets/stripe_publishable_key
- run/secrets/stripe_secret_key
- run/secrets/test_secret
> remove dummy files and config call

- app/models/user.rb
Fixes #
We are currently having issues with validation errors, that appear to be related to prod/ staging geolocation.
> attempt to print validation errors

- app/controllers/api/v1/users_controller.rb
> Validate error print

- .rubocop_todo.yml
- config/environments/staging.rb
Fixes #
gotta add a staging.rb config
> add staging.rb

- bin/deploy
Update current-context and specifically staging. 
No specific issue, just resolving the fact I'm not always around to help. 
makes it so merges to master will update both staging and prod and not require kubectl access
> Master updates staging and prod

- bin/deploy
Fixes #
Removing the prefix to match infra names
> removed the operationcode- prefix to match the infra changes

- Dockerfile
- Makefile
- lib/tasks/schools_from_yml.rake
- Ruby 2.3.3 is EOL, update to the latest supported Ruby version
- Fixes on small bug in a rake task that broke specs
Tested this with:
```
make minty-fresh
make setup
make test
```
Fixes #484
> Update to Ruby 2.6.3

- config/code_schools.yml
Updates the yaml to match current prod code schools.
Fixes #492
Will have to update the staging once these are in it.
> update codeschools to match prod

- Dockerfile
- Makefile
- lib/tasks/schools_from_yml.rake
Reverts OperationCode/operationcode_backend#503
This Pr requires updating how infra runs sidekiq. 
https://github.com/OperationCode/operationcode_infra/pull/84
This has been corrected so I can revert the revert.
> Revert "Revert "Update to Ruby 2.6.3""
