- Makefile
By adding `build` functions to `make setup` Docker images will also be pulled and prepared locally, so that a new developer can be immediately productive.
Fixes #20
> `make setup` should also build Docker images

- config/code_schools.yml
Dev Bootcamp Chicago moved locations about 6 months ago. This change will reflect the most up-to-date address.
Fixes #65
> Fix Dev Bootcamp address - resolves issue #65

- app/controllers/api/v1/sessions_controller.rb
Removes the unused variable assignment of `user =`.  This [was reported here](https://codeclimate.com/github/OperationCode/operationcode_backend/app/controllers/api/v1/sessions_controller.rb#issue_59429d20957fc90001000068) though code climate.
Fixes #48
> bug/Removes unused assignment - resolves issue 48

- Gemfile
- Gemfile.lock
- app/lib/json_web_token.rb
If `jwt_secret` is unavailable, the `rescue` block will capture the error, without halting the program.  	This implementation follows existing [precedence for capturing and logging errors for jwt_secret](https://github.com/OperationCode/operationcode_backend/blob/master/app/lib/json_web_token.rb#L15-L18).
Alternatively, we can be more aggressive, and `raise` an error, if that is the desired approach.  That will, however, halt the program, which might be what you are looking for here?
This PR also adds the Awesome Print gem for development and testing envs.  This speeds up my production when debugging and using the `rails console`, by increasing the readability of any code that is printed out.
It does so by providing structure and highlighting.
Ruby Gems link: …
> Feature/raise error on missing jwt secret - resolves issue 39

- app/models/user.rb
I changed the regex provided:   ` /@/`
To:     `/\A.*@.*\z/ `
A broader explanation of my regex is provided as follows:
`\A` : starts the string 
`.*`  : picks up any amount of any single character
`@`  : picks up the @ in the email
`.*` : picks up any amount of any single character
`\z `: ends the string
Fixes #47
> fixed regex for email validation

- CONTRIBUTING.md
This corrects the Markdown used to point to sections within the contribution guide
Fixes #81
> Working links to fragments in the contribution guide

- .gitignore
Adds lines to `.gitignore` from entering "MacOS", "Linux", "Windows", "Ruby", "Rails", "Sublime", "VisualStudioCode", "JetBrains", and "RubyMine" into [GitIgnore.io](https://gitignore.io). No lines were removed - existing .gitignore lines were simply moved.
Resolves #95
> Resolve #95 - Update .gitignore

- config/code_schools.yml
Removes Dev Bootcamp from code_schools.yml, since Dev Bootcamp has shut down.
Fixes #107 
I didn't create a test since it didn't seem appropriate for this particular issue. I wanted to visually test it, but I wasn't sure how exactly to do that with the frontend and backend projects split. I'm able to get the Ruby on Rails home screen up when I run `make` - is there a way to connect up the front end so that I can see changes I make? I have the frontend project set up locally as well.
> Remove Dev Bootcamp from code_schools.yml

- app/views/user_mailer/welcome.html.erb
Mentee link was pointing to an Airtable form that updated the 'Mentees' sheet in Airtable, but that sheet is not being as actively monitored as the 'Mentor Request' sheet.  The new link points to the Airtable form that updates the 'Mentor Request' sheet in Airtable, which is actively monitored and also posts notifications to our #mentors-internal Slack channel.
No current issue for this, but related to [front-end issue 341](https://github.com/OperationCode/operationcode_frontend/issues/341) and [back-end issue 155](https://github.com/OperationCode/operationcode_backend/issues/155) . Mentees were filling out the older Airtable form and not being contacted as intended.
> Update mentee form link in welcome email

- config/code_schools.yml
Added the information about the $4,000 scholarship as a note.
Set the "Hardware included" to true.
The information about Turing School was updated to reflect the fact that they offer two $4,000 scholarships that veterans are eligible to apply for and use as tuition credit.
The "Hardware included" flag was set to "true" to reflect the fact that Turing School offers classes on hardware.
Fixes #157
> Update information for Turing School of Software and Design

- config/code_schools.yml
- Emails have been added for each code school.
- New locations were added to Galvanize, Hack Reactor, Sabio, General Assembly, Epicodus, DeVry, AppAcademy, Tech Elevator, and Coding Dojo.
- Duplicated entry for Tradecraft was removed.
- Starter League were removed, as they've merged with Fullstack Academy.
- Other small updates and corrections to addresses or "has_online".
Fixes #36
> resolve #36

- app/controllers/api/v1/sessions_controller.rb
If a user signs up as a mentor, they are added to the mentors list in Discourse automatically. I wasn't able to figure out how to test the payload (tried signing up a new user and viewing the console, but didn't see anything related to SSO), so I hope this works!
This is an update to my prior pull request since the tests were not passing. As @hpjaj suggested, I updated my master branch and the tests appear to be passing.
Fixes #117
> Automatically add mentor to Discourse

- config/code_schools.yml
- Updated Sabio logo url in code_schools.yaml to use `sabio.png`
Fixes #178
There needs to be coordinated deployment between the front and backends.
> Updated Sabio logo url in code_schools.yaml to use png

- config/code_schools.yml
This PR adds an `cincy code it bootcamp` entry in our /code_schools api response and adds it to our /code_schools page. This PR is dependent on https://github.com/OperationCode/operationcode_frontend/pull/727
Fixes #190
> Add cincy code it bootcamps object

- app/controllers/api/v1/email_list_recipients_controller.rb
- app/jobs/add_user_to_send_grid_job.rb
- test/controllers/api/v1/email_list_recipients_controller_test.rb
- test/jobs/add_user_to_send_grid_job_test.rb
- Updates SendGrid background job to receive valid argument
- Permits `email` param in `email_list_recipients_controller`
All of the tests were giving false positives, because in testing, `perform_now` is called in the background.
Also, during manual testing, `perform_now` was being used.
The catch is, `perform_later` does not accept an array wrapped Struct as an argument, despite the fact that it allows arrays.
As such, this logic was migrated from the controller, to the job itself.
Now the job is receiving a string as as an arg, which `perform_later` does accept.
Also, the `email` param in the new `email_list_recipients_controller` was not being explicitly permitted.  This was not causing any issues, but is a best practice that I initially overlooked.
> bug/fixes 'add guest to sendgrid contact list' endpoint 

- app/controllers/api/v1/email_list_recipients_controller.rb
- app/jobs/add_user_to_send_grid_job.rb
- test/controllers/api/v1/email_list_recipients_controller_test.rb
- test/jobs/add_user_to_send_grid_job_test.rb
Sidekiq appears to not support key word arguments:  https://github.com/mperham/sidekiq/issues/2372
As such, this PR changes the key word arguments to positional arguments.
After testing this in local development, with a temporary SendGrid API key, I was able to: 
- run the back and frontend repos together
- submit an email address in the UI
- confirm the email address was added to our SendGrid marketing contacts list
- confirm no sidekiq errors in the server logs
Fixes #222
> bug/guest emails not being added to SendGrid

- app/controllers/api/v1/code_schools_controller.rb
- test/controllers/api/v1/code_schools_controller_test.rb
Adds the authenticate_user! before action for create, update and destroy on codeschools controller.
Updates tests for each of these actions.
Fixes #239
>  Authenticate Code Schools Controller and Update Tests

- README.md
Hi there! 👋 
I work at Skylight, and had chatted over email with @nellshamrell about adding a Skylight performance badge to the Operation Code README as part of the Skylight for Open Source program. This PR follows up on the [recent addition](https://github.com/OperationCode/operationcode_backend/pull/249) of Skylight instrumentation added by @chancancode.
Please do let me know if there is a better place to put this badge; I followed what I have seen other open source repositories do, but I can move it if you'd prefer!
> Add Skylight performance monitoring badge

- Gemfile.lock
Resolves rack-protection security vulnerability by upgrading the rack-protection gem to the version suggested by GitHub.
Fixes #264
> Updates rack-protection gem

- Makefile
- lib/tasks/update_schools_logo.rake
- test/lib/update_school_logos_test.rb
Creates rake tasks to update `CodeSchool` records' `logo` attribute to use aws hosted images instead of GitHub's assets.
Fixes #284
> Created update:school_logos and helper schools:populate rake cmds

- app/lib/seed_team_members.rb
- config/team_members.yml
- lib/tasks/seed_members.rake
Uses the new list of team and board members so that the front end is properly reflected.
Fixes #230
Okay so, Rather than delete most of them and duplicate the work, that was done with the new SeedTeamMember, using active record delete records within the team seeding. 
I'm not sure what's happening with the chapter leaders, but I think that's getting worked out. Was told to remove them all for now. 
Performed a clean `make bundle; make setup; make test; ` then ran the rake task. 
[output gist](https://gist.github.com/wimo7083/42907ea573b8481d55f82c2c2627d034)
> Update team and board members

- Gemfile
- Gemfile.lock
- app/admin/admin_user.rb
- app/controllers/api/v1/social_users_controller.rb
- app/controllers/application_controller.rb
- app/models/ability.rb
- app/models/admin_user.rb
- app/models/role.rb
- config/initializers/active_admin.rb
- db/migrate/20180408172532_add_role_id_to_admin_user.rb
- db/schema.rb
Currently in order to give a user access to the admin dashboard, we have to grant them "super admin" privileges.
We want to be able to give people access to view and filter, but not the ability to create or update any records.
This PR establishes the foundation for this tiered access to the admin dashboard's offerings.  Namely it:
Fixes #293
> 293 tiered admin access

- app/admin/code_school.rb
- app/admin/location.rb
- app/models/ability.rb
Gives admins the ability to conduct CRUD actions on the `CodeSchool` and `Location` models.  
Fixes #294
> 294 code schools in admin dashboard

- app/admin/code_school.rb
- app/admin/user.rb
There are certain fields that the database automatically populates on our behalf, and should not be manually adjusted.  This PR removes those fields from the admin dashboard's forms.
Fixes #304
> Removes db auto-filled fields from admin forms

- app/admin/team_member.rb
- app/controllers/api/v1/team_members_controller.rb
- config/board_members.yml
- config/team_members.yml
- db/migrate/20180416024105_add_email_to_team_member.rb
- db/schema.rb
In order to finish up front-end issue https://github.com/OperationCode/operationcode_frontend/issues/943, the API call to https://api.operationcode.org/api/v1/team_members needs to return an `email` field for executive staff team members (non-board). This `email` field is already in the static client-side data ([executiveStaff.js](https://github.com/OperationCode/operationcode_frontend/blob/master/src/scenes/home/team/executiveStaff.js)) that will be replaced by the fetched API data.
--------------------
- David Molina: `david@operationcode.org`
- Jennifer Wiedeman: `jennifer@operationcode.org`
- Amy Tan: `amy@operationcode.org`
- Nell Shamrell: `nell@operationcode.org`
- Ashley Templet: `ashley@operationcode.org`
- Kelly MacLeod: `kelly@operationcode.org`
- Jameel Matin: …
> 309 email for team members

- apiary.apib
- app/controllers/api/v1/slack_users_controller.rb
- app/lib/json_web_token.rb
- config/routes.rb
- config/secrets.yml
- test/controllers/api/v1/slack_users_controller_test.rb
This PR:
- Creates a `py_bot_auth_key` in the `config/secrets.yml`:
- In the dev area, set to 'some_secret_key'
- In prod, set to `<%= ENV["PY_BOT_AUTH_KEY"] %>`
- In kubernetes, set the auth key
- Creates a new 'health check/access' BE endpoint:
- `/api/v1/slack_users/access`
- Calls the JWT method to decode the key
- If it is valid, that gives access to endpoint
- Else raise, renders error
- I will give @wimo7083 a JWT encoded version of the key 
- This will need to be passed in the auth headers for every request from PyBot (i.e. `Authorization: Bearer <encoded token>`)
- PyBot calls the new BE endpoints 
- BE confirms the validity of the token, and responds with the requested payload
Fixes #321
> 321 grant py bot api access

- Makefile
- apiary.apib
- app/controllers/api/v1/code_schools_controller.rb
- app/serializers/code_school_serializer.rb
- db/migrate/20180420192231_add_is_partner_to_code_schools.rb
- db/schema.rb
- lib/tasks/update_is_partner_for_code_schools.rake
- test/factories/code_schools.rb
- test/models/code_schools_test.rb
Add is_partner to the CodeSchool table. Defaulting to false and null false
Add attr to serializer
Add attr to strong params
Update apiary docs
Add spec illustrating presence
Add attr to factory, default to false
Creates a new rake task to set any existing, relevant CodeSchool records in prod to is_partner: true
Fixes #275
> Add is_partner to the CodeSchool table

- app/lib/git_hub/settings.rb
- config/secrets.yml
- run/secrets/git_hub_client_id
- run/secrets/git_hub_client_secret
- test/lib/git_hub/authentication_test.rb
In order to utilize the [aggregated GitHub stats feature](https://github.com/OperationCode/operationcode_backend/pull/153), we need the [GitHub authentication](https://developer.github.com/v3/#authentication) `client_id` and `client_secret` set.
Fixes #335
> Favors Rails secrets for auth config

- app/lib/git_hub/authentication.rb
- app/lib/git_hub/settings.rb
- config/secrets.yml
- test/lib/git_hub/authentication_test.rb
The [O_AUTH_2_KEY_SECRET](https://developer.github.com/v3/#authentication) strategy was capping our rate limit at 60 (vs. 5000).
This PR updates the strategy to `O_AUTH_2_TOKEN`.
> Updates GitHub aggregation strategy to OAuth 2 token 

- app/admin/scholarship.rb
- app/admin/scholarship_application.rb
- app/models/ability.rb
- db/seeds.rb
- test/factories/scholarship_applications.rb
- test/factories/users.rb
Gives admins the ability to conduct CRUD actions on the Scholarship and ScholarshipApplication 
models. Currently this has to be done through prod's rails console.
Adds a Resource for Scholarship to ActiveAdmin
Adds a Resource for ScholarshipApplication to ActiveAdmin
Updates ability.rb with the proper permissions 
Fixes #349
> Adds new resources to ActiveAdmin for `Scholarship` and `ScholarshipApplication`

- app/admin/code_school.rb
#Description of changes
This PR adds is_partner to app/admin/code_school.rb in the "permit_params", "index do end block", and the form block.
#Issue Resolved
is_partner should now show up in the admin dashboard for code schools.
> Adds is_partner to active admin codeschool

- .rubocop.yml
- apiary.apib
- app/admin/user.rb
- app/controllers/api/v1/users_controller.rb
- app/models/user.rb
- db/migrate/20180711212702_add_militarystatus_to_user.rb
- db/schema.rb
- test/models/user_test.rb
Adds a column for `military_status`, which is currently not present on `users`. This will allow the information we request regarding a military spouse / active duty in signup flow to save to the DB.
Part of fixing #373 (some frontend work needed)
_It's been a while for me. Please review._
> Add military_status to user (fixes #373)

- app/controllers/api/v1/airtable/mentorships_controller.rb
- app/lib/airtable/mentorship.rb
- test/controllers/api/v1/airtable/mentorships_controller_test.rb
Passes along the incoming `email` value for a Mentor Request from the React front-end to Airtable, so mentors have a reliable way of communicating with a mentee in case they are not yet on Slack.
This change is needed to assist with front-end issue https://github.com/OperationCode/operationcode_frontend/issues/971.  There are some proposed ideas to automatically populate the user's email field via PyBot and Slack integrations, but they are not yet implemented. cc @wimo7083 
Fuzzy hypothesis: Looks like passing along the email value to Airtable may also be needed to get the PyBot to populate the request to Slack ??
Fixes #377
> Pass email value to Airtable as part of mentor request

- .rubocop.yml
- app/models/user.rb
- test/models/user_test.rb
Temporarily turns off leader emails due to bug with the sidekiq queue related to the database.
Temporarily turns off slack emails since @hollomancer loves to invite our new people (also a bug)
I also don't use git much, and I included a rubocop fix that should be separate (and it is), and my partner is wondering why I'm not spending time with her but I needed to get this fix out.
Fixes #390 #380 #384
> Fixes few bugs

- Makefile
- docs/setup/docker_setup.md
This will make a clean state and prevent errors but scope it to the actual project instead of system wide.
<details>
#<summary>make minty-fresh following a make minty-fresh</summary>
<code>
C:\Users\wimo7\Desktop\back [make_nuke +1 ~0 -0 !]> make nuke
docker-compose down --rmi all --volumes
Removing network operationcodebackend_default
WARNING: Network operationcodebackend_default not found.
Removing image operationcodebackend_web
ERROR: Failed to remove image for service bundle: 404 Client Error: Not Found ("b'No such image: operationcodebackend_web:latest'")
Removing image postgres
ERROR: Failed to remove image for service operationcode-psql: 404 Client Error: Not Found ("b'No such image: postgres:latest'")
Removing image redis:latest
ERROR: Failed to remove image for service redis: 404 …
> changed makefile to use docker fresh start

- docker-compose.yml
* allow the sidekiq service to reuse the image built for the web service
* change the web service to bind to only the loopback interface (i.e. `localhost`) to avoid sharing your development backend with everyone in the coffee shop
* ~update the PG and Redis services to also bind their ports to host's loopback to allow devs to run the Ruby bits on the host OS while reusing the docker'd database and Redis store~ (removed from this PR because of port conflicts in Travis)
Each of these bullets were added in separate commits, so each change is reviewable in isolation from the others.
> refine the docker-compose config

- test/factories/code_schools.rb
- test/factories/locations.rb
Laziness in a factory lets an attr be random. Without putting these in Ruby blocks, FactoryGirl will call Faker for an attribute once when a factory is first used and then use that value for every create() and
build() thereafter. 
~Fixes #~
This is helpful in development for being able to generate a bunch of sample data in the database that looks different. It will also ensure that the records for the test suite are randomish to make sure tests aren't passing because of some underlying, but unintentional consistency.
> wrap some factory attrs in blocks to make them lazy

- app/controllers/api/v1/users_controller.rb
- app/models/user.rb
- config/environments/test.rb
- test/controllers/api/v1/users_controller_test.rb
- test/models/user_test.rb
This fixes a race condition between the web process creating the user record and a worker process picking up the job to use the user record to add them to SendGrid.
The race shows itself in an error from Sidekiq:
ActiveJob::DeserializationError: Error while trying to deserialize
arguments: Couldn't find User with 'id'=1234
An alternative to #402 to fix the same AddToSendGridJob errors seen in production.
The `welcome_user()` method is the thing scheduling a job that is trying to find a user. Making the ActiveRecord lifecycle callbacks responsible for business processes can be painful to test and maintain. This change removes the welcoming of a user from the User model's callbacks and makes the controller action that creates users responsible for welcoming them. Asserting that the job is …
> schedule welcoming jobs after user has been saved to the database

- .rubocop.yml
- db/schema.rb
Add `db/schema.rb` to the all exceptions list as it's auto generated.
Revert the `db/schema.rb` to the format that has the extra line (auto generated).
Fixes #374
> Fix: Issue Linter corrections

- Makefile
Currently:
```
C:\Users\wimo7\Desktop\back [make_console_fix +1 ~0 -0 !]> make console-sandbox
make: Nothing to be done for 'console-sandbox'.
```
There is a target for this though:
https://github.com/OperationCode/operationcode_backend/blob/b34ad45cc77a0c86d3918681e83066cf5d58a060/Makefile#L31
While the `.PHONY` is properly declared there is no valid target due to a tab:
Fixes using a makefile target to run the console with the operation code docker instance.
> modify makefile to fix issue with console-sandbox target

- app/models/scholarship_application.rb
Removes the verification for users of id.me status. 
Removed the user_is_verified hook.
Removed the user_is_verified method
Removed the verified [delegate](https://apidock.com/rails/Module/delegate) - which is something I just learned about, but I still don't understand.
I left the FactoryGirl specifying a verified status, since it doesn't matter now. 
I haven't tested any verified routes before. This is a non-tested change, please don't merge unless you are able to test or assist me with testing this. 
I think I need to run both FE and BE locally, register a user and then test that this works locally. I'm going to try and get to that tomorrow. 
Fixes #408
> remove validation of veteran status due to changed requirements

- app/controllers/api/v1/email_list_recipients_controller.rb
- app/jobs/add_guest_to_send_grid_job.rb
- app/jobs/add_user_to_send_grid_job.rb
- app/jobs/application_job.rb
- app/jobs/send_email_to_leaders_job.rb
- app/jobs/slack_jobs.rb
- app/jobs/slack_jobs/inviter_job.rb
- app/jobs/slack_jobs/notifier_job.rb
- app/models/user.rb
- config/initializers/active_admin.rb
- config/routes.rb
- test/controllers/api/v1/email_list_recipients_controller_test.rb
- test/jobs/add_guest_to_send_grid_job_test.rb
- test/jobs/add_user_to_send_grid_job_test.rb
- test/models/user_test.rb
- test/test_helper.rb
This adds the Sidekiq web UI to the admin section under `/admin/sidekiq` for some better insight into the job queues. It also turns all the ActiveJob job classes into Sidekiq::Worker classes.
My recommendation is to commit to Sidekiq as the backend's background job processor. Some benefits of making backend's jobs full-fledged Sidekiq::Worker classes:
* more refined controls over when and how a job is executed
* easier test configuration to prevent the actual scheduling of jobs during a test run into a development environment
* increased visibility into the state of jobs through the Sidekiq administrative web UI
Fixes #405
> add Sidekiq web UI to admin section; go max-Sidekiq with jobs

- .rubocop.yml
- Makefile
- Makefile.in
- apiary.apib
- app/admin/job.rb
- db/migrate/20180531004341_create_jobs.rb
- db/schema.rb
- db/seeds.rb
- test/factories/jobs.rb
> Merge job changes into head branch

- .gitignore
- app/controllers/api/v1/resources_controller.rb
- app/lib/git_hub/issues.rb
- app/lib/git_hub/presenter.rb
- app/lib/git_hub/pull_requests.rb
- app/models/git_hub_statistic.rb
- lib/tasks/schools_from_yml.rake
- test/models/request_test.rb
- test/requests/git_hub/issues_test.rb
- test/requests/git_hub/pull_requests_test.rb
1. Reduce verbosity for tests
This reduces the amount of chatter seen while running unit tests. In cases where the rake file printed out debug information this adds an override so that the tests don't have this show. 
Not only is the easier to find unit test errors but stdout can be slow and the tests here run a little faster. 
```powershell
docker-compose run web bash -c 'export RAILS_ENV=test && rake db:test:prepare && rake test && rubocop'
Starting operationcodebackend_bundle_1             ... done
Starting operationcodebackend_operationcode-psql_1 ... done
Starting operationcodebackend_redis_1              ... done
Run options: --seed 61055
......................................S.........................................................S.................................................. …
```
> Test chatters

- test/mailers/user_mailer_test.rb
Fixed the mailer test so names with special characters are escaped properly in the test expectations
Fixes #423
> Fixed the mailer test

- app/lib/git_hub/client.rb
- test/controllers/api/v1/airtable/mentorships_controller_test.rb
- test/controllers/api/v1/code_schools_controller_test.rb
- test/controllers/api/v1/slack_users_controller_test.rb
- test/lib/git_hub/authentication_test.rb
- test/lib/git_hub/committer_test.rb
- test/lib/send_grid_client/guest_test.rb
- test/models/code_schools_test.rb
- test/models/user_test.rb
- test/requests/airtable/mentorship_test.rb
- test/requests/git_hub/client_test.rb
- test/requests/git_hub/issues_test.rb
- test/requests/git_hub/page_compiler_test.rb
- test/requests/git_hub/pull_requests_test.rb
Swaps out use of `assert` with `assert_equals` and fixed a timezone issue when running tests locally.
Based off #421
> Test cleanup

- README.md
Looks like the quickstart instructions in the README got separated from
the quickstart heading. This moves them back.
Moves the quickstart instructions under the quickstart heading to make documentation clearer. Also removes a duplicate link in the instructions list.
None
> Move quickstart instructions into quickstart section

- config/initializers/devise.rb
Devise config currently has `secret_key` set in the config, this overrides `secret_key_base` which is set in the environment variables. This removes the `secret_key` from the configs for clarity. 
Fixes #441
> remove secret_key, in place of environment variable

- app/models/user.rb
- test/models/user_test.rb
We only want to validate zip codes on creation as there are individuals who don't have zipcodes and wish to edit their account. 
Fixes # Front end issue.
> Only validate zip on create

- config/database.yml
This change should fix staging, instead of using harded username for production database we should be using the values listed in the kubernetes secrets which are namespaced. 
Fixes Staging?
Summary:
Apparently both production and production-staging pods are using their own namespaced secrets storage. The secrets had a 2 values that were of importance:
`POSTGRES_HOST` and `POSTGRES_PASSWORD`
`POSTGRES_HOST` contained a different value, and in AWS it was shown that both of those exist and were paired correctly.
But in AWS the username for each was different and the k8s secrets showed they both used the same name as indicated in the config file.
Additionally they both used the same `POSTGRES_PASSWORD` but after inspecting our credentials management it was seen that prod and staging have two …
> Postgres env secrets

- config/database.yml
> add user and password values to prod

- config/database.yml
Reverts OperationCode/operationcode_backend#459
> Revert "add user and password values to prod"

- Dockerfile
Hello,
The use of COPY is preferred over ADD when additional functionalities of ADD are not being used (like spraying the contents of a tar in a folder).
Ref:https://docs.docker.com/engine/articles/dockerfile_best-practices/#add-or-copy
Thanks.
New issue.
> Use COPY instead of ADD in Dockerfile

- docker-compose.yml
Resolves an error generated when running `make test`.
Error:
```
ERROR: for operationcodebackend_sidekiq_1  Cannot start service sidekiq: b'OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \\"sidekiq\\": executable file not found in $PATH": unknown'
```
No related ticket, this was an issue picked up in the slack chat
> Add bundle prefix to sidekiq

- Makefile
We're isolated in the docker containers so we _shouldn't_ run into conflicts here, but this closely reflects the commands as you'd want to run them locally, if you weren't using a Makefile. So, I'd consider it more a "documentation" fix than anything
Also cleaned up some trailing empty spaces on commands. 
This might be considered a style/preference but I consider it more of a good rule to follow when using bundler. Please feel free to close it if it doesn't add any value.
No issues closed. This is a general documentation/cleanup suggestion
> Add bundle prefixes to rails/rake/rubocop commands

- Dockerfile
Uses built-in system tools to parse the Gemfile.lock & pull out the
bundler version used to build the Gemfile.lock, ensuring that's the same
version of bundler used to bundle inside the container
- Resolves the warning:
> Warning: the running version of Bundler (1.14.6) is older than the version that created the lockfile (1.17.1). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`."
- Helps prevent issues with bundle version conflicts/differences in
the future
- Updates rubygems to ensure we have all the latest patches and
updates. Per the output from inside the container, this includes a
number of patches dating back to 2017-03-16 which include at least five
(5) CVE fixes
No related ticket. This was noted while going thru the backend setup …
> Install version of bundler from Gemfile

- Dockerfile
- Makefile
- lib/tasks/schools_from_yml.rake
Reverts OperationCode/operationcode_backend#500
This is failing in k8s due to missing sidekiq exectuable. We rolled back manually in k8s.
> Revert "Update to Ruby 2.6.3"
